# -*- coding: utf-8 -*-
"""correlacao_regressao_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwJwxZVEq-pA3By_ktpAhRA-iVoua5jI
"""

#bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import requests
import zipfile
import io

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#dataset

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00294/CCPP.zip"

r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

#carregar dataset

df = pd.read_excel('CCPP/Folds5x2_pp.xlsx')
df.head(10)

df.info()
df.describe()

#questao 1 - Correlação com a variável alvo (PE)
corr = df.corr()

print((corr['PE']).sort_values(ascending = False))

#questão 2 - Correlação entre as variáveis

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Mapa de Correlação")
plt.show()

#separar as variaveis questao 3
X = df[['AT', 'V', 'AP', 'RH']]
y = df['PE']

#treino e teste questao 3
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#treinar modelo questao 3
modelo = LinearRegression()
modelo.fit(X_train, y_train)

#previsoes questao 3
y_pred = modelo.predict(X_test)
print(y_pred)

#questão 4 Avaliar o modelo
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

#previsao x real
plt.scatter(y_test, y_pred)
plt.xlabel("Valor Real")
plt.ylabel("Valor Previsto")
plt.title("Real vs Previsto")
plt.show()