# -*- coding: utf-8 -*-
"""correlacao_regressao_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwJwxZVEq-pA3By_ktpAhRA-iVoua5jI
"""

#bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import requests
import zipfile
import io

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#dataset baixar e extrair
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00294/CCPP.zip"

r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

#procurando o nome da pasta
import os
os.listdir()

os.listdir('CCPP')

#carregar dataset
df = pd.read_excel('CCPP/Folds5x2_pp.xlsx')

# Visualizar dados
df.head()

df.info()
df.describe()

#questao 1 orrelação geral
corr = df.corr()

# Correlação com PE
corr_pe = corr['PE'].sort_values(ascending=False)
print(corr_pe)

#Visualização
plt.figure(figsize=(8,5))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Mapa de Correlação")
plt.show()

#2- Correlação entre variáveis independentes

corr_indep = df[['AT', 'V', 'AP', 'RH']].corr()
print(corr_indep)

plt.figure(figsize=(8,5))
sns.heatmap(corr_indep, annot=True, cmap='coolwarm')
plt.title('Correlação entre variáveis independentes')
plt.show()

#treino e teste questao 3
X = df[['AT', 'V', 'AP', 'RH']]
y = df['PE']

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#treinar modelo questao 3
modelo = LinearRegression()
modelo.fit(X_train, y_train)

print("Intercepto:", modelo.intercept_)
print("Coeficientes:", modelo.coef_)

#previsoes questao 3
y_pred = modelo.predict(X_test)
print(y_pred)

#questão 4 Avaliar o modelo
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("R²:", r2)
print("RMSE:", rmse)
print("MAE:", mae)

#grafico de comparação
plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Valor real")
plt.ylabel("Valor previsto")
plt.title("Real vs Previsto")
plt.show()